##
## https://github.com/sidigi/bitrix-docker/blob/master/docker-compose.yml
## https://github.com/spiritabsolute/bitrix-env-dev/blob/master/docker-compose.yml
##


version: '3'

volumes:
  bx-logs-push:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${BX_LOGS_PATH}/push

services:

  redis:
    image: redis
    container_name: bx-redis
    restart: always
    networks:
      bx:
        aliases:
          - redis

  push-server-sub:
    image: repodocker.office.bitrix.ru/bx-push
    container_name: bx-push-sub
    restart: always
    env_file: .env
    ports:
      - ${BX_PUSH_SUB_PORT}:${BX_PUSH_SUB_PORT}
    labels:
      - traefik.port=${BX_PUSH_SUB_PORT}
      - traefik.protocol=http
      - traefik.frontend.rule=Host:${BX_PUSH_SUB_HOST}
    volumes:
      - bx-logs-push:/var/log/push-server
    networks:
      bx:
        aliases:
          - ${BX_PUSH_SUB_HOST}

  push-server-pub:
    image: repodocker.office.bitrix.ru/bx-push
    container_name: bx-push-pub
    restart: always
    env_file: .env
    volumes:
      - bx-logs-push:/var/log/push-server
    networks:
      bx:
        aliases:
          - ${BX_PUSH_PUB_HOST}

networks:
  bx:
