##
## https://github.com/sidigi/bitrix-docker/blob/master/docker-compose.yml
## https://github.com/spiritabsolute/bitrix-env-dev/blob/master/docker-compose.yml
##


version: '3'
volumes:
  bx-logs-mysql80:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${BX_LOGS_PATH}/mysql80
  bx-mysql80:

services:
  mysql80:
    image: repodocker.office.bitrix.ru/bx-mysql80
    container_name: bx-mysql80
    restart: always
    env_file: .env
    ports:
      - 3306:3308
    volumes:
      - bx-logs/mysql80:/var/log/mysql
      - bx-mysql80:/var/lib/mysql
    networks:
      bx:
        aliases:
          - mysql80

networks:
  bx:
