##
## https://github.com/sidigi/bitrix-docker/blob/master/docker-compose.yml
## https://github.com/spiritabsolute/bitrix-env-dev/blob/master/docker-compose.yml
##


version: '2'

services:

  mounts:
    image: busybox
    container_name: bx-www
    volumes:
      - ${BX_PUBLIC_HTML_PATH}:/var/www/public_html
      - ${BX_MODULES_PATH}:/media/bitrix/modules

  memcache:
    image: memcached:alpine
    container_name: bx-memcache
    restart: always
    networks:
      bx:
        aliases:
          - memcache

  nginx:
    extends:
      file: ./common-services.yml
      service: server
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    container_name: bx-nginx
    restart: always
    environment:
      - BX_DEFAULT_HOST=${BX_DEFAULT_HOST}
      - BX_DEFAULT_LOCAL_DOMAIN=${BX_DEFAULT_LOCAL_DOMAIN}
      - BX_HOST_AUTOCREATE=${BX_HOST_AUTOCREATE}
      - BX_PUSH_PUB_HOST=${BX_PUSH_PUB_HOST}
      - BX_PUSH_PUB_PORT=${BX_PUSH_PUB_PORT}
      - BX_PUSH_SUB_HOST=${BX_PUSH_SUB_HOST}
      - BX_PUSH_SUB_PORT=${BX_PUSH_SUB_PORT}
    volumes_from:
      - mounts
    volumes:
      - ${BX_LOGS_PATH}/nginx:/var/log/nginx
    networks:
      bx:
        aliases:
          - nginx

networks:
  bx:
