##
## https://github.com/sidigi/bitrix-docker/blob/master/docker-compose.yml
## https://github.com/spiritabsolute/bitrix-env-dev/blob/master/docker-compose.yml
##


version: '3'

volumes:
  bx-logs-mysql57:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${BX_LOGS_PATH}/mysql57
  bx-mysql57:

services:
  mysql57:
    image: repodocker.office.bitrix.ru/bx-mysql57
    container_name: bx-mysql57
    restart: always
    env_file: .env
    ports:
      - 3307:3306
    volumes:
      - bx-logs-mysql57:/var/log/mysql
      - bx-mysql57:/var/lib/mysql
    networks:
      bx:
        aliases:
          - mysql57
          - mysql

