##
## https://github.com/sidigi/bitrix-docker/blob/master/docker-compose.yml
## https://github.com/spiritabsolute/bitrix-env-dev/blob/master/docker-compose.yml
##


version: '3'

volumes:
  bx-logs-php74:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${BX_LOGS_PATH}/php74

services:
  php74:
    image: repodocker.office.bitrix.ru/bx-php74
    container_name: bx-php74
    restart: always
    env_file: .env
    volumes:
      - bx-logs-php74:/var/log/php-fpm
      - bx-public:/var/www/public_html
      - bx-modules:/media/bitrix/modules
    networks:
      bx:
        aliases:
          - php74

